# Generated by Django 5.1.2 on 2024-10-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0002_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingbooking',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
