# Generated by Django 5.1.2 on 2024-11-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0003_meetingbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingbooking',
            name='mandatory_attendees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingbooking',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingbooking',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
